http:
  port: 8080
apiEndpoints:
  api:
    host: localhost
    paths: "/"
serviceEndpoints:
  user-service:
    url: "http://localhost:7001"

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: user-service
              changeOrigin: true
